(function(){var a="\n//# sourceURL=",k="' of type ",n='&lt;script type="text/javascript" src="',p="SCRIPT",r="array",t="complete",u="function",v="google.charts.load",w="hasOwnProperty",x="number",y="object",z="pre-45",A="propertyIsEnumerable",B="string",C="text/javascript",D="toLocaleString";function E(){return function(b){return b}}function F(){return function(){}}function G(b){return function(){return this[b]}}var I,J=J||{};J.scope={};
J.Wp=function(b,c,d){if(null==b)throw new TypeError("The 'this' value for String.prototype."+d+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+d+" must not be a regular expression");return b+""};J.Ih=!1;J.im=!1;J.jm=!1;J.defineProperty=J.Ih||typeof Object.defineProperties==u?Object.defineProperty:function(b,c,d){b!=Array.prototype&amp;&amp;b!=Object.prototype&amp;&amp;(b[c]=d.value)};
J.Kj=function(b){return"undefined"!=typeof window&amp;&amp;window===b?b:"undefined"!=typeof global&amp;&amp;null!=global?global:b};J.global=J.Kj(this);J.Vk=function(b){if(b){for(var c=J.global,d=["Promise"],e=0;e&lt;d.length-1;e++){var f=d[e];f in c||(c[f]={});c=c[f]}d=d[d.length-1];e=c[d];b=b(e);b!=e&amp;&amp;null!=b&amp;&amp;J.defineProperty(c,d,{configurable:!0,writable:!0,value:b})}};
J.Hq=function(b,c,d){b instanceof String&amp;&amp;(b=String(b));for(var e=b.length,f=0;f&lt;e;f++){var g=b[f];if(c.call(d,g,f,b))return{ak:f,Ol:g}}return{ak:-1,Ol:void 0}};J.Ai="jscomp_symbol_";J.ug=function(){J.ug=F();J.global.Symbol||(J.global.Symbol=J.Symbol)};J.zl=0;J.Symbol=function(b){return J.Ai+(b||"")+J.zl++};
J.Hd=function(){J.ug();var b=J.global.Symbol.iterator;b||(b=J.global.Symbol.iterator=J.global.Symbol("iterator"));typeof Array.prototype[b]!=u&amp;&amp;J.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return J.gf(this)}});J.Hd=F()};J.gf=function(b){var c=0;return J.wk(function(){return c&lt;b.length?{done:!1,value:b[c++]}:{done:!0}})};J.wk=function(b){J.Hd();b={next:b};b[J.global.Symbol.iterator]=function(){return this};return b};
J.Tg=function(b){J.Hd();var c=b[Symbol.iterator];return c?c.call(b):J.gf(b)};J.$h=!1;
J.Vk(function(b){function c(b){this.$=g.xa;this.ja=void 0;this.Wb=[];var c=this.jd();try{b(c.resolve,c.reject)}catch(q){c.reject(q)}}function d(){this.Ma=null}function e(b){return b instanceof c?b:new c(function(c){c(b)})}if(b&amp;&amp;!J.$h)return b;d.prototype.hf=function(b){null==this.Ma&amp;&amp;(this.Ma=[],this.Pi());this.Ma.push(b)};d.prototype.Pi=function(){var b=this;this.jf(function(){b.wj()})};var f=J.global.setTimeout;d.prototype.jf=function(b){f(b,0)};d.prototype.wj=function(){for(;this.Ma&amp;&amp;this.Ma.length;){var b=
this.Ma;this.Ma=[];for(var c=0;c&lt;b.length;++c){var d=b[c];delete b[c];try{d()}catch(H){this.Qi(H)}}}this.Ma=null};d.prototype.Qi=function(b){this.jf(function(){throw b;})};var g={xa:0,Ja:1,ka:2};c.prototype.jd=function(){function b(b){return function(e){d||(d=!0,b.call(c,e))}}var c=this,d=!1;return{resolve:b(this.$k),reject:b(this.$d)}};c.prototype.$k=function(b){if(b===this)this.$d(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof c)this.rl(b);else{a:switch(typeof b){case y:var d=
null!=b;break a;case u:d=!0;break a;default:d=!1}d?this.Zk(b):this.Lf(b)}};c.prototype.Zk=function(b){var c=void 0;try{c=b.then}catch(q){this.$d(q);return}typeof c==u?this.sl(c,b):this.Lf(b)};c.prototype.$d=function(b){this.ph(g.ka,b)};c.prototype.Lf=function(b){this.ph(g.Ja,b)};c.prototype.ph=function(b,c){if(this.$!=g.xa)throw Error("Cannot settle("+b+", "+c|"): Promise already settled in state"+this.$);this.$=b;this.ja=c;this.yj()};c.prototype.yj=function(){if(null!=this.Wb){for(var b=this.Wb,
c=0;c&lt;b.length;++c)b[c].call(),b[c]=null;this.Wb=null}};var h=new d;c.prototype.rl=function(b){var c=this.jd();b.ic(c.resolve,c.reject)};c.prototype.sl=function(b,c){var d=this.jd();try{b.call(c,d.resolve,d.reject)}catch(H){d.reject(H)}};c.prototype.then=function(b,d){function e(b,c){return typeof b==u?function(c){try{f(b(c))}catch(ca){g(ca)}}:c}var f,g,h=new c(function(b,c){f=b;g=c});this.ic(e(b,f),e(d,g));return h};c.prototype["catch"]=function(b){return this.then(void 0,b)};c.prototype.ic=function(b,
c){function d(){switch(e.$){case g.Ja:b(e.ja);break;case g.ka:c(e.ja);break;default:throw Error("Unexpected state: "+e.$);}}var e=this;null==this.Wb?h.hf(d):this.Wb.push(function(){h.hf(d)})};c.resolve=e;c.reject=function(b){return new c(function(c,d){d(b)})};c.race=function(b){return new c(function(c,d){for(var f=J.Tg(b),g=f.next();!g.done;g=f.next())e(g.value).ic(c,d)})};c.all=function(b){var d=J.Tg(b),f=d.next();return f.done?e([]):new c(function(b,c){function g(c){return function(d){h[c]=d;l--;
0==l&amp;&amp;b(h)}}var h=[],l=0;do h.push(void 0),l++,e(f.value).ic(g(h.length-1),c),f=d.next();while(!f.done)})};return c});var K=K||{};K.global=this;K.P=function(b){return void 0!==b};K.L=function(b){return typeof b==B};K.ek=function(b){return"boolean"==typeof b};K.Tb=function(b){return typeof b==x};
K.od=function(b,c,d){b=b.split(".");d=d||K.global;b[0]in d||!d.execScript||d.execScript("var "+b[0]);for(var e;b.length&amp;&amp;(e=b.shift());)!b.length&amp;&amp;K.P(c)?d[e]=c:d=d[e]&amp;&amp;d[e]!==Object.prototype[e]?d[e]:d[e]={}};K.define=function(b,c){K.od(b,c)};K.ea=!0;K.ba="en";K.bd=!0;K.yi=!1;K.Wh=!K.ea;K.Ge=!1;K.Gs=function(b){if(K.Md())throw Error("goog.provide can not be used within a goog.module.");K.tf(b)};K.tf=function(b,c){K.od(b,c)};K.Fi=/^[a-zA-Z_$][a-zA-Z0-9._$]*$/;
K.Vd=function(b){if(!K.L(b)||!b||-1==b.search(K.Fi))throw Error("Invalid module identifier");if(!K.Md())throw Error("Module "+b+" has been loaded incorrectly. Note, modules cannot be loaded as normal scripts. They require some kind of pre-processing step. You're likely trying to load a module via a script tag or as a part of a concatenated bundle without rewriting the module. For more info see: https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide.");
if(K.na.Wd)throw Error("goog.module may only be called once per module.");K.na.Wd=b};K.Vd.get=function(){return null};K.Vd.cr=function(){return null};K.na=null;K.Md=function(){return null!=K.na};K.Vd.ld=function(){K.na.ld=!0};K.xt=function(b){if(K.Wh)throw b=b||"",Error("Importing test-only code into non-debug environment"+(b?": "+b:"."));};K.Nq=F();K.vb=function(b){b=b.split(".");for(var c=K.global,d;d=b.shift();)if(K.eb(c[d]))c=c[d];else return null;return c};
K.mr=function(b,c){c=c||K.global;for(var d in b)c[d]=b[d]};K.kp=function(b,c,d,e){if(K.De){var f;b=b.replace(/\\/g,"/");var g=K.la;e&amp;&amp;"boolean"!==typeof e||(e=e?{module:"goog"}:{});for(var h=0;f=c[h];h++)g.Ub[f]=b,g.Qd[b]=e;for(e=0;c=d[e];e++)b in g.gb||(g.gb[b]={}),g.gb[b][c]=!0}};K.$t=!1;K.$m=!0;K.Hk=function(b){K.global.console&amp;&amp;K.global.console.error(b)};K.Ss=F();K.La="";K.Sa=F();K.jp=function(){throw Error("unimplemented abstract method");};
K.lp=function(b){b.Id=void 0;b.ar=function(){if(b.Id)return b.Id;K.ea&amp;&amp;(K.zg[K.zg.length]=b);return b.Id=new b}};K.zg=[];K.hi=!0;K.vi=K.ea;K.Fk={};K.De=!1;K.Ye="detect";K.Bi="transpile.js";
K.De&amp;&amp;(K.la={Qd:{},Ub:{},gb:{},Bh:{},me:{},tb:{}},K.tg=function(){var b=K.global.document;return null!=b&amp;&amp;"write"in b},K.zj=function(){if(K.P(K.global.Be)&amp;&amp;K.L(K.global.Be))K.La=K.global.Be;else if(K.tg()){var b=K.global.document;var c=b.currentScript;b=c?[c]:b.getElementsByTagName(p);for(c=b.length-1;0&lt;=c;--c){var d=b[c].src,e=d.lastIndexOf("?");e=-1==e?d.length:e;if("base.js"==d.substr(e-7,7)){K.La=d.substr(0,e-7);break}}}},K.Gd=function(b,c){(K.global.Cm||K.Wl)(b,c)&amp;&amp;(K.la.me[b]=!0)},K.fi=!(K.global.atob||
!K.global.document||!K.global.document.all),K.dh=!1,K.ck=function(b,c,d){K.Gd("",'goog.retrieveAndExec_("'+b+'", '+c+", "+d+");")},K.Yd=[],K.du=function(b,c){return K.hi&amp;&amp;K.P(K.global.JSON)?"goog.loadModule("+K.global.JSON.stringify(c+a+b+"\n")+");":'goog.loadModule(function(exports) {"use strict";'+c+"\n;return exports});\n//# sourceURL="+b+"\n"},K.Dk=function(){var b=K.Yd.length;if(0&lt;b){var c=K.Yd;K.Yd=[];for(var d=0;d&lt;b;d++)K.Wg(c[d])}K.dh=!1},K.ms=function(b){K.Eg(b)&amp;&amp;K.Li(b)&amp;&amp;K.Wg(K.La+K.Bd(b))},
K.Eg=function(b){var c=(b=K.Bd(b))&amp;&amp;K.la.Qd[b]||{},d=c.lang||"es3";return b&amp;&amp;("goog"==c.module||K.$g(d))?K.La+b in K.la.tb:!1},K.Li=function(b){if((b=K.Bd(b))&amp;&amp;b in K.la.gb)for(var c in K.la.gb[b])if(!K.pk(c)&amp;&amp;!K.Eg(c))return!1;return!0},K.Wg=function(b){if(b in K.la.tb){var c=K.la.tb[b];delete K.la.tb[b];K.Vj(c)}},K.gs=F(),K.Vl=function(b){K.global.document.write(n+b+'"&gt;\x3c/script&gt;')},K.Mi=function(b){var c=K.global.document,d=c.createElement("script");d.type=C;d.src=b;d.defer=!1;d.async=!1;c.head.appendChild(d)},
K.Wl=function(b,c){if(K.tg()){var d=K.global.document;if(!K.Ge&amp;&amp;d.readyState==t){if(/\bdeps.js$/.test(b))return!1;throw Error('Cannot write "'+b+'" after document load');}void 0===c?K.fi?(K.dh=!0,c=" onreadystatechange='goog.onScriptLoad_(this, "+ ++K.Sg+")' ",d.write(n+b+'"'+c+"&gt;\x3c/script&gt;")):K.Ge?K.Mi(b):K.Vl(b):d.write('&lt;script type="text/javascript"&gt;'+K.Wk(c)+"\x3c/script&gt;");return!0}return!1},K.Wk=function(b){return b.replace(/&lt;\/(SCRIPT)/ig,"\\x3c/$1")},K.$g=function(b){if("always"==K.Ye)return!0;
if("never"==K.Ye)return!1;K.Gc||(K.Gc=K.gj());if(b in K.Gc)return K.Gc[b];throw Error("Unknown language mode: "+b);},K.Gc=null,K.Sg=0,K.As=function(b,c){b.readyState==t&amp;&amp;K.Sg==c&amp;&amp;K.Dk();return!0},K.eu=function(b){function c(b){if(!(b in f.me||b in f.Bh)){f.Bh[b]=!0;if(b in f.gb)for(var g in f.gb[b])if(!K.pk(g))if(g in f.Ub)c(f.Ub[g]);else throw Error("Undefined nameToPath for "+g);b in e||(e[b]=!0,d.push(b))}}var d=[],e={},f=K.la;c(b);for(var g=0;g&lt;d.length;g++)b=d[g],K.la.me[b]=!0;var h=K.na;K.na=
null;for(g=0;g&lt;d.length;g++)if(b=d[g]){var l=f.Qd[b]||{},m=K.$g(l.lang||"es3");"goog"==l.module||m?K.ck(K.La+b,"goog"==l.module,m):K.Gd(K.La+b)}else throw K.na=h,Error("Undefined script input");K.na=h},K.Bd=function(b){return b in K.la.Ub?K.la.Ub[b]:null},K.zj(),K.global.Dm||K.Gd(K.La+"deps.js"));K.Ed=null;K.Ml=function(){if(null==K.Ed){try{var b=!eval('"use strict";let x = 1; function f() { return typeof x; };f() == "number";')}catch(c){b=!1}K.Ed=b}return K.Ed};
K.Tl=function(b){return"(function(){"+b+"\n;})();\n"};K.fs=function(b){var c=K.na;try{K.na={Wd:void 0,ld:!1};if(K.za(b))var d=b.call(void 0,{});else if(K.L(b))K.Ml()&amp;&amp;(b=K.Tl(b)),d=K.Ck.call(void 0,b);else throw Error("Invalid module definition");var e=K.na.Wd;if(!K.L(e)||!e)throw Error('Invalid module name "'+e+'"');K.na.ld?K.tf(e,d):K.vi&amp;&amp;Object.seal&amp;&amp;typeof d==y&amp;&amp;null!=d&amp;&amp;Object.seal(d);K.Fk[e]=d}finally{K.na=c}};K.Ck=function(b){eval(b);return{}};
K.ts=function(b){b=b.split("/");for(var c=0;c&lt;b.length;)"."==b[c]?b.splice(c,1):c&amp;&amp;".."==b[c]&amp;&amp;b[c-1]&amp;&amp;".."!=b[c-1]?b.splice(--c,2):c++;return b.join("/")};K.zk=function(b){if(K.global.Rh)return K.global.Rh(b);try{var c=new K.global.XMLHttpRequest;c.open("get",b,!1);c.send();return 0==c.status||200==c.status?c.responseText:null}catch(d){return null}};K.Us=F();
K.Rt=function(b,c){var d=K.global.$jscomp;d||(K.global.$jscomp=d={});var e=d.je;if(!e){var f=K.La+K.Bi,g=K.zk(f);if(g){eval(g+a+f);if(K.global.$gwtExport&amp;&amp;K.global.$gwtExport.$jscomp&amp;&amp;!K.global.$gwtExport.$jscomp.transpile)throw Error('The transpiler did not properly export the "transpile" method. $gwtExport: '+JSON.stringify(K.global.$gwtExport));K.global.$jscomp.je=K.global.$gwtExport.$jscomp.transpile;d=K.global.$jscomp;e=d.je}}if(!e){var h=" requires transpilation but no transpiler was found.";
h+=' Please add "//javascript/closure:transpiler" as a data dependency to ensure it is included.';e=d.je=function(b,c){K.Hk(c+h);return b}}return e(b,c)};
K.aa=function(b){var c=typeof b;if(c==y)if(b){if(b instanceof Array)return r;if(b instanceof Object)return c;var d=Object.prototype.toString.call(b);if("[object Window]"==d)return y;if("[object Array]"==d||typeof b.length==x&amp;&amp;"undefined"!=typeof b.splice&amp;&amp;"undefined"!=typeof b.propertyIsEnumerable&amp;&amp;!b.propertyIsEnumerable("splice"))return r;if("[object Function]"==d||"undefined"!=typeof b.call&amp;&amp;"undefined"!=typeof b.propertyIsEnumerable&amp;&amp;!b.propertyIsEnumerable("call"))return u}else return"null";
else if(c==u&amp;&amp;"undefined"==typeof b.call)return y;return c};K.Rr=function(b){return null===b};K.eb=function(b){return null!=b};K.isArray=function(b){return K.aa(b)==r};K.Pb=function(b){var c=K.aa(b);return c==r||c==y&amp;&amp;typeof b.length==x};K.Dr=function(b){return K.ia(b)&amp;&amp;typeof b.getFullYear==u};K.za=function(b){return K.aa(b)==u};K.ia=function(b){var c=typeof b;return c==y&amp;&amp;null!=b||c==u};K.ng=function(b){return b[K.Wa]||(b[K.Wa]=++K.Fl)};K.pr=function(b){return!!b[K.Wa]};
K.Xk=function(b){null!==b&amp;&amp;"removeAttribute"in b&amp;&amp;b.removeAttribute(K.Wa);try{delete b[K.Wa]}catch(c){}};K.Wa="closure_uid_"+(1E9*Math.random()&gt;&gt;&gt;0);K.Fl=0;K.$q=K.ng;K.Os=K.Xk;K.cj=function(b){var c=K.aa(b);if(c==y||c==r){if(b.clone)return b.clone();c=c==r?[]:{};for(var d in b)c[d]=K.cj(b[d]);return c}return b};K.Ui=function(b,c,d){return b.call.apply(b.bind,arguments)};
K.Ti=function(b,c,d){if(!b)throw Error();if(2&lt;arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var d=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(d,e);return b.apply(c,d)}}return function(){return b.apply(c,arguments)}};K.bind=function(b,c,d){K.bind=Function.prototype.bind&amp;&amp;-1!=Function.prototype.bind.toString().indexOf("native code")?K.Ui:K.Ti;return K.bind.apply(null,arguments)};
K.fb=function(b,c){var d=Array.prototype.slice.call(arguments,1);return function(){var c=d.slice();c.push.apply(c,arguments);return b.apply(this,c)}};K.os=function(b,c){for(var d in c)b[d]=c[d]};K.now=K.bd&amp;&amp;Date.now||function(){return+new Date};
K.Vj=function(b){if(K.global.execScript)K.global.execScript(b,"JavaScript");else if(K.global.eval){if(null==K.oc)if(K.global.eval("var _evalTest_ = 1;"),"undefined"!=typeof K.global._evalTest_){try{delete K.global._evalTest_}catch(e){}K.oc=!0}else K.oc=!1;if(K.oc)K.global.eval(b);else{var c=K.global.document,d=c.createElement(p);d.type=C;d.defer=!1;d.appendChild(c.createTextNode(b));c.body.appendChild(d);c.body.removeChild(d)}}else throw Error("goog.globalEval not available");};K.oc=null;
K.Yq=function(b,c){function d(b){b=b.split("-");for(var c=[],d=0;d&lt;b.length;d++)c.push(e(b[d]));return c.join("-")}function e(b){return K.xf[b]||b}if("."==String(b).charAt(0))throw Error('className passed in goog.getCssName must not start with ".". You passed: '+b);var f=K.xf?"BY_WHOLE"==K.mj?e:d:E();b=c?b+"-"+f(c):f(b);return K.global.Qh?K.global.Qh(b):b};K.gt=function(b,c){K.xf=b;K.mj=c};K.dr=function(b,c){c&amp;&amp;(b=b.replace(/\{\$([^}]+)}/g,function(b,e){return null!=c&amp;&amp;e in c?c[e]:b}));return b};
K.er=E();K.Cf=function(b,c){K.od(b,c,void 0)};K.Gq=function(b,c,d){b[c]=d};K.bb=function(b,c){function d(){}d.prototype=c.prototype;b.Nc=c.prototype;b.prototype=new d;b.prototype.constructor=b;b.Si=function(b,d,g){for(var e=Array(arguments.length-2),f=2;f&lt;arguments.length;f++)e[f-2]=arguments[f];return c.prototype[d].apply(b,e)}};
K.Si=function(b,c,d){var e=arguments.callee.caller;if(K.yi||K.ea&amp;&amp;!e)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(e.Nc){for(var f=Array(arguments.length-1),g=1;g&lt;arguments.length;g++)f[g-1]=arguments[g];return e.Nc.constructor.apply(b,f)}f=Array(arguments.length-2);for(g=2;g&lt;arguments.length;g++)f[g-2]=arguments[g];g=!1;for(var h=b.constructor;h;h=h.Nc&amp;&amp;h.Nc.constructor)if(h.prototype[c]===
e)g=!0;else if(g)return h.prototype[c].apply(b,f);if(b[c]===e)return b.constructor.prototype[c].apply(b,f);throw Error("goog.base called from a method of one name to a method of a different name");};K.scope=function(b){if(K.Md())throw Error("goog.scope is not supported within a goog.module.");b.call(K.global)};
K.qa=function(b,c){var d=c.constructor,e=c.wl;d&amp;&amp;d!=Object.prototype.constructor||(d=function(){throw Error("cannot instantiate an interface (no constructor defined).");});d=K.qa.hj(d,b);b&amp;&amp;K.bb(d,b);delete c.constructor;delete c.wl;K.qa.ff(d.prototype,c);null!=e&amp;&amp;(e instanceof Function?e(d):K.qa.ff(d,e));return d};K.qa.ui=K.ea;
K.qa.hj=function(b,c){function d(){var c=b.apply(this,arguments)||this;c[K.Wa]=c[K.Wa];this.constructor===d&amp;&amp;e&amp;&amp;Object.seal instanceof Function&amp;&amp;Object.seal(c);return c}if(!K.qa.ui)return b;var e=!K.qa.sk(c);return d};K.qa.sk=function(b){return b&amp;&amp;b.prototype&amp;&amp;b.prototype[K.Di]};K.qa.Pe=["constructor",w,"isPrototypeOf",A,D,"toString","valueOf"];
K.qa.ff=function(b,c){for(var d in c)Object.prototype.hasOwnProperty.call(c,d)&amp;&amp;(b[d]=c[d]);for(var e=0;e&lt;K.qa.Pe.length;e++)d=K.qa.Pe[e],Object.prototype.hasOwnProperty.call(c,d)&amp;&amp;(b[d]=c[d])};K.Kt=F();K.Di="goog_defineClass_legacy_unsealable";
K.gj=function(){function b(b,c){e?d[b]=!0:c()?d[b]=!1:e=d[b]=!0}function c(b){try{return!!eval(b)}catch(h){return!1}}var d={es3:!1},e=!1,f=K.global.navigator&amp;&amp;K.global.navigator.userAgent?K.global.navigator.userAgent:"";b("es5",function(){return c("[1,].length==1")});b("es6",function(){var b=f.match(/Edge\/(\d+)(\.\d)*/i);return b&amp;&amp;15&gt;Number(b[1])?!1:c('(()=&gt;{"use strict";class X{constructor(){if(new.target!=String)throw 1;this.x=42}}let q=Reflect.construct(X,[],String);if(q.x!=42||!(q instanceof String))throw 1;for(const a of[2,3]){if(a==2)continue;function f(z={a}){let a=0;return z.a}{function f(){return 0;}}return f()==3}})()')});
b("es6-impl",function(){return!0});b("es7",function(){return c("2 ** 2 == 4")});b("es8",function(){return c("async () =&gt; 1, true")});return d};K.debug={};K.debug.Error=function(b){if(Error.captureStackTrace)Error.captureStackTrace(this,K.debug.Error);else{var c=Error().stack;c&amp;&amp;(this.stack=c)}b&amp;&amp;(this.message=String(b))};K.bb(K.debug.Error,Error);K.debug.Error.prototype.name="CustomError";K.a={};K.a.fa={Ia:1,km:2,fc:3,zm:4,bn:5,an:6,ro:7,Im:8,Zc:9,Um:10,Xh:11,fo:12};K.f={};K.f.Yc=!1;K.f.Zh=!1;K.f.af={Ne:"\u00a0"};K.f.startsWith=function(b,c){return 0==b.lastIndexOf(c,0)};K.f.endsWith=function(b,c){var d=b.length-c.length;return 0&lt;=d&amp;&amp;b.indexOf(c,d)==d};K.f.aj=function(b){return 0==K.f.mf("tel:",b.substr(0,4))};K.f.Up=function(b,c){return 0==K.f.mf(c,b.substr(b.length-c.length,c.length))};K.f.Vp=function(b,c){return b.toLowerCase()==c.toLowerCase()};
K.f.yl=function(b,c){for(var d=b.split("%s"),e="",f=Array.prototype.slice.call(arguments,1);f.length&amp;&amp;1&lt;d.length;)e+=d.shift()+f.shift();return e+d.join("%s")};K.f.aq=function(b){return b.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")};K.f.Kd=function(b){return/^[\s\xa0]*$/.test(b)};K.f.Gr=function(b){return 0==b.length};K.f.Sb=K.f.Kd;K.f.gk=function(b){return K.f.Kd(K.f.Mk(b))};K.f.Fr=K.f.gk;K.f.Br=function(b){return!/[^\t\n\r ]/.test(b)};K.f.yr=function(b){return!/[^a-zA-Z]/.test(b)};
K.f.Sr=function(b){return!/[^0-9]/.test(b)};K.f.zr=function(b){return!/[^a-zA-Z0-9]/.test(b)};K.f.Yr=function(b){return" "==b};K.f.Zr=function(b){return 1==b.length&amp;&amp;" "&lt;=b&amp;&amp;"~"&gt;=b||"\u0080"&lt;=b&amp;&amp;"\ufffd"&gt;=b};K.f.It=function(b){return b.replace(/(\r\n|\r|\n)+/g," ")};K.f.$i=function(b){return b.replace(/(\r\n|\r|\n)/g,"\n")};K.f.vs=function(b){return b.replace(/\xa0|\s/g," ")};K.f.us=function(b){return b.replace(/\xa0|[ \t]+/g," ")};
K.f.$p=function(b){return b.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"")};K.f.trim=K.bd&amp;&amp;String.prototype.trim?function(b){return b.trim()}:function(b){return b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};K.f.trimLeft=function(b){return b.replace(/^[\s\xa0]+/,"")};K.f.trimRight=function(b){return b.replace(/[\s\xa0]+$/,"")};K.f.mf=function(b,c){b=String(b).toLowerCase();c=String(c).toLowerCase();return b&lt;c?-1:b==c?0:1};
K.f.bh=function(b,c,d){if(b==c)return 0;if(!b)return-1;if(!c)return 1;for(var e=b.toLowerCase().match(d),f=c.toLowerCase().match(d),g=Math.min(e.length,f.length),h=0;h&lt;g;h++){d=e[h];var l=f[h];if(d!=l)return b=parseInt(d,10),!isNaN(b)&amp;&amp;(c=parseInt(l,10),!isNaN(c)&amp;&amp;b-c)?b-c:d&lt;l?-1:1}return e.length!=f.length?e.length-f.length:b&lt;c?-1:1};K.f.wr=function(b,c){return K.f.bh(b,c,/\d+|\D+/g)};K.f.Cj=function(b,c){return K.f.bh(b,c,/\d+|\.\d+|\D+/g)};K.f.ys=K.f.Cj;K.f.Zt=function(b){return encodeURIComponent(String(b))};
K.f.Yt=function(b){return decodeURIComponent(b.replace(/\+/g," "))};K.f.ah=function(b,c){return b.replace(/(\r\n|\r|\n)/g,c?"&lt;br /&gt;":"&lt;br&gt;")};
K.f.ua=function(b,c){if(c)b=b.replace(K.f.ne,"&amp;amp;").replace(K.f.Me,"&amp;lt;").replace(K.f.Je,"&amp;gt;").replace(K.f.Te,"&amp;quot;").replace(K.f.We,"&amp;#39;").replace(K.f.Oe,"&amp;#0;"),K.f.Yc&amp;&amp;(b=b.replace(K.f.He,"&amp;#101;"));else{if(!K.f.Gh.test(b))return b;-1!=b.indexOf("&amp;")&amp;&amp;(b=b.replace(K.f.ne,"&amp;amp;"));-1!=b.indexOf("&lt;")&amp;&amp;(b=b.replace(K.f.Me,"&amp;lt;"));-1!=b.indexOf("&gt;")&amp;&amp;(b=b.replace(K.f.Je,"&amp;gt;"));-1!=b.indexOf('"')&amp;&amp;(b=b.replace(K.f.Te,"&amp;quot;"));-1!=b.indexOf("'")&amp;&amp;(b=b.replace(K.f.We,"&amp;#39;"));-1!=b.indexOf("\x00")&amp;&amp;
(b=b.replace(K.f.Oe,"&amp;#0;"));K.f.Yc&amp;&amp;-1!=b.indexOf("e")&amp;&amp;(b=b.replace(K.f.He,"&amp;#101;"))}return b};K.f.ne=/&amp;/g;K.f.Me=/&lt;/g;K.f.Je=/&gt;/g;K.f.Te=/"/g;K.f.We=/'/g;K.f.Oe=/\x00/g;K.f.He=/e/g;K.f.Gh=K.f.Yc?/[\x00&amp;&lt;&gt;"'e]/:/[\x00&amp;&lt;&gt;"']/;K.f.xh=function(b){return K.f.contains(b,"&amp;")?!K.f.Zh&amp;&amp;"document"in K.global?K.f.yh(b):K.f.Il(b):b};K.f.Vt=function(b,c){return K.f.contains(b,"&amp;")?K.f.yh(b,c):b};
K.f.yh=function(b,c){var d={"&amp;amp;":"&amp;","&amp;lt;":"&lt;","&amp;gt;":"&gt;","&amp;quot;":'"'};var e=c?c.createElement("div"):K.global.document.createElement("div");return b.replace(K.f.di,function(b,c){var f=d[b];if(f)return f;"#"==c.charAt(0)&amp;&amp;(c=Number("0"+c.substr(1)),isNaN(c)||(f=String.fromCharCode(c)));f||(e.innerHTML=b+" ",f=e.firstChild.nodeValue.slice(0,-1));return d[b]=f})};
K.f.Il=function(b){return b.replace(/&amp;([^;]+);/g,function(b,d){switch(d){case "amp":return"&amp;";case "lt":return"&lt;";case "gt":return"&gt;";case "quot":return'"';default:return"#"!=d.charAt(0)||(d=Number("0"+d.substr(1)),isNaN(d))?b:String.fromCharCode(d)}})};K.f.di=/&amp;([^;\s&lt;&amp;]+);?/g;K.f.Rl=function(b){return K.f.ah(b.replace(/  /g," &amp;#160;"),void 0)};K.f.Fs=function(b){return b.replace(/(^|[\n ]) /g,"$1"+K.f.af.Ne)};
K.f.Jt=function(b,c){for(var d=c.length,e=0;e&lt;d;e++){var f=1==d?c:c.charAt(e);if(b.charAt(0)==f&amp;&amp;b.charAt(b.length-1)==f)return b.substring(1,b.length-1)}return b};K.f.truncate=function(b,c,d){d&amp;&amp;(b=K.f.xh(b));b.length&gt;c&amp;&amp;(b=b.substring(0,c-3)+"...");d&amp;&amp;(b=K.f.ua(b));return b};K.f.Tt=function(b,c,d,e){d&amp;&amp;(b=K.f.xh(b));e&amp;&amp;b.length&gt;c?(e&gt;c&amp;&amp;(e=c),b=b.substring(0,c-e)+"..."+b.substring(b.length-e)):b.length&gt;c&amp;&amp;(e=Math.floor(c/2),b=b.substring(0,e+c%2)+"..."+b.substring(b.length-e));d&amp;&amp;(b=K.f.ua(b));return b};
K.f.fe={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","&lt;":"&lt;"};K.f.yc={"'":"\\'"};K.f.quote=function(b){b=String(b);for(var c=['"'],d=0;d&lt;b.length;d++){var e=b.charAt(d),f=e.charCodeAt(0);c[d+1]=K.f.fe[e]||(31&lt;f&amp;&amp;127&gt;f?e:K.f.Af(e))}c.push('"');return c.join("")};K.f.Fq=function(b){for(var c=[],d=0;d&lt;b.length;d++)c[d]=K.f.Af(b.charAt(d));return c.join("")};
K.f.Af=function(b){if(b in K.f.yc)return K.f.yc[b];if(b in K.f.fe)return K.f.yc[b]=K.f.fe[b];var c=b.charCodeAt(0);if(31&lt;c&amp;&amp;127&gt;c)var d=b;else{if(256&gt;c){if(d="\\x",16&gt;c||256&lt;c)d+="0"}else d="\\u",4096&gt;c&amp;&amp;(d+="0");d+=c.toString(16).toUpperCase()}return K.f.yc[b]=d};K.f.contains=function(b,c){return-1!=b.indexOf(c)};K.f.nf=function(b,c){return K.f.contains(b.toLowerCase(),c.toLowerCase())};K.f.iq=function(b,c){return b&amp;&amp;c?b.split(c).length-1:0};
K.f.Cb=function(b,c,d){var e=b;0&lt;=c&amp;&amp;c&lt;b.length&amp;&amp;0&lt;d&amp;&amp;(e=b.substr(0,c)+b.substr(c+d,b.length-c-d));return e};K.f.remove=function(b,c){return b.replace(c,"")};K.f.Ls=function(b,c){c=new RegExp(K.f.Zd(c),"g");return b.replace(c,"")};K.f.Rs=function(b,c,d){c=new RegExp(K.f.Zd(c),"g");return b.replace(c,d.replace(/\$/g,"$$$$"))};K.f.Zd=function(b){return String(b).replace(/([-()\[\]{}+?*.$\^|,:#&lt;!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
K.f.repeat=String.prototype.repeat?function(b,c){return b.repeat(c)}:function(b,c){return Array(c+1).join(b)};K.f.Ds=function(b,c,d){b=K.P(d)?b.toFixed(d):String(b);d=b.indexOf(".");-1==d&amp;&amp;(d=b.length);return K.f.repeat("0",Math.max(0,c-d))+b};K.f.Mk=function(b){return null==b?"":String(b)};K.f.Pp=function(b){return Array.prototype.join.call(arguments,"")};K.f.ir=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^K.now()).toString(36)};
K.f.Jb=function(b,c){var d=0;b=K.f.trim(String(b)).split(".");c=K.f.trim(String(c)).split(".");for(var e=Math.max(b.length,c.length),f=0;0==d&amp;&amp;f&lt;e;f++){var g=b[f]||"",h=c[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==g[0].length&amp;&amp;0==h[0].length)break;d=K.f.fd(0==g[1].length?0:parseInt(g[1],10),0==h[1].length?0:parseInt(h[1],10))||K.f.fd(0==g[2].length,0==h[2].length)||K.f.fd(g[2],h[2]);g=g[3];h=h[3]}while(0==d)}return d};
K.f.fd=function(b,c){return b&lt;c?-1:b&gt;c?1:0};K.f.qr=function(b){for(var c=0,d=0;d&lt;b.length;++d)c=31*c+b.charCodeAt(d)&gt;&gt;&gt;0;return c};K.f.Jl=2147483648*Math.random()|0;K.f.rq=function(){return"goog_"+K.f.Jl++};K.f.Nt=function(b){var c=Number(b);return 0==c&amp;&amp;K.f.Kd(b)?NaN:c};K.f.Lr=function(b){return/^[a-z]+([A-Z][a-z]*)*$/.test(b)};K.f.$r=function(b){return/^([A-Z][a-z]*)+$/.test(b)};K.f.Mt=function(b){return String(b).replace(/\-([a-z])/g,function(b,d){return d.toUpperCase()})};
K.f.Pt=function(b){return String(b).replace(/([A-Z])/g,"-$1").toLowerCase()};K.f.Qt=function(b,c){c=K.L(c)?K.f.Zd(c):"\\s";return b.replace(new RegExp("(^"+(c?"|["+c+"]+":"")+")([a-z])","g"),function(b,c,f){return c+f.toUpperCase()})};K.f.Tp=function(b){return String(b.charAt(0)).toUpperCase()+String(b.substr(1)).toLowerCase()};K.f.parseInt=function(b){isFinite(b)&amp;&amp;(b=String(b));return K.L(b)?/^\s*-?0x/i.test(b)?parseInt(b,16):parseInt(b,10):NaN};
K.f.Dt=function(b,c,d){b=b.split(c);for(var e=[];0&lt;d&amp;&amp;b.length;)e.push(b.shift()),d--;b.length&amp;&amp;e.push(b.join(c));return e};K.f.cs=function(b,c){if(c)typeof c==B&amp;&amp;(c=[c]);else return b;for(var d=-1,e=0;e&lt;c.length;e++)if(""!=c[e]){var f=b.lastIndexOf(c[e]);f&gt;d&amp;&amp;(d=f)}return-1==d?b:b.slice(d+1)};
K.f.zq=function(b,c){var d=[],e=[];if(b==c)return 0;if(!b.length||!c.length)return Math.max(b.length,c.length);for(var f=0;f&lt;c.length+1;f++)d[f]=f;for(f=0;f&lt;b.length;f++){e[0]=f+1;for(var g=0;g&lt;c.length;g++)e[g+1]=Math.min(e[g]+1,d[g+1]+1,d[g]+Number(b[f]!=c[g]));for(g=0;g&lt;d.length;g++)d[g]=e[g]}return e[c.length]};K.m={};K.m.oa=K.ea;K.m.$b=function(b,c){c.unshift(b);K.debug.Error.call(this,K.f.yl.apply(null,c));c.shift()};K.bb(K.m.$b,K.debug.Error);K.m.$b.prototype.name="AssertionError";K.m.Uh=function(b){throw b;};K.m.md=K.m.Uh;K.m.Fa=function(b,c,d,e){var f="Assertion failed";if(d){f+=": "+d;var g=e}else b&amp;&amp;(f+=": "+b,g=c);b=new K.m.$b(""+f,g||[]);K.m.md(b)};K.m.kt=function(b){K.m.oa&amp;&amp;(K.m.md=b)};K.m.assert=function(b,c){K.m.oa&amp;&amp;!b&amp;&amp;K.m.Fa("",null,c,Array.prototype.slice.call(arguments,2));return b};
K.m.ma=function(b){K.m.oa&amp;&amp;K.m.md(new K.m.$b("Failure"+(b?": "+b:""),Array.prototype.slice.call(arguments,1)))};K.m.Gp=function(b,c){K.m.oa&amp;&amp;!K.Tb(b)&amp;&amp;K.m.Fa("Expected number but got %s: %s.",[K.aa(b),b],c,Array.prototype.slice.call(arguments,2));return b};K.m.Jp=function(b,c){K.m.oa&amp;&amp;!K.L(b)&amp;&amp;K.m.Fa("Expected string but got %s: %s.",[K.aa(b),b],c,Array.prototype.slice.call(arguments,2));return b};
K.m.up=function(b,c){K.m.oa&amp;&amp;!K.za(b)&amp;&amp;K.m.Fa("Expected function but got %s: %s.",[K.aa(b),b],c,Array.prototype.slice.call(arguments,2));return b};K.m.Hp=function(b,c){K.m.oa&amp;&amp;!K.ia(b)&amp;&amp;K.m.Fa("Expected object but got %s: %s.",[K.aa(b),b],c,Array.prototype.slice.call(arguments,2));return b};K.m.rp=function(b,c){K.m.oa&amp;&amp;!K.isArray(b)&amp;&amp;K.m.Fa("Expected array but got %s: %s.",[K.aa(b),b],c,Array.prototype.slice.call(arguments,2));return b};
K.m.sp=function(b,c){K.m.oa&amp;&amp;!K.ek(b)&amp;&amp;K.m.Fa("Expected boolean but got %s: %s.",[K.aa(b),b],c,Array.prototype.slice.call(arguments,2));return b};K.m.tp=function(b,c){!K.m.oa||K.ia(b)&amp;&amp;b.nodeType==K.a.fa.Ia||K.m.Fa("Expected Element but got %s: %s.",[K.aa(b),b],c,Array.prototype.slice.call(arguments,2));return b};K.m.vp=function(b,c,d){!K.m.oa||b instanceof c||K.m.Fa("Expected instanceof %s but got %s.",[K.m.mg(c),K.m.mg(b)],d,Array.prototype.slice.call(arguments,3));return b};
K.m.Ip=function(){for(var b in Object.prototype)K.m.ma(b+" should not be enumerable in Object.prototype.")};K.m.mg=function(b){return b instanceof Function?b.displayName||b.name||"unknown type name":b instanceof Object?b.constructor.displayName||b.constructor.name||Object.prototype.toString.call(b):null===b?"null":typeof b};K.f.ap=F();K.f.H=function(){this.Mc="";this.zi=K.f.H.Ze};K.f.H.prototype.va=!0;K.f.H.prototype.ha=G("Mc");K.f.H.prototype.toString=function(){return"Const{"+this.Mc+"}"};K.f.H.u=function(b){if(b instanceof K.f.H&amp;&amp;b.constructor===K.f.H&amp;&amp;b.zi===K.f.H.Ze)return b.Mc;K.m.ma("expected object of type Const, got '"+b+"'");return"type_error:Const"};K.f.H.from=function(b){return K.f.H.lj(b)};K.f.H.Ze={};K.f.H.lj=function(b){var c=new K.f.H;c.Mc=b;return c};K.f.H.EMPTY=K.f.H.from("");K.j={};K.Ca=K.bd;K.j.Aa=!1;K.j.Uk=function(b){return b[b.length-1]};K.j.bs=K.j.Uk;K.j.indexOf=K.Ca&amp;&amp;(K.j.Aa||Array.prototype.indexOf)?function(b,c,d){return Array.prototype.indexOf.call(b,c,d)}:function(b,c,d){d=null==d?0:0&gt;d?Math.max(0,b.length+d):d;if(K.L(b))return K.L(c)&amp;&amp;1==c.length?b.indexOf(c,d):-1;for(;d&lt;b.length;d++)if(d in b&amp;&amp;b[d]===c)return d;return-1};
K.j.lastIndexOf=K.Ca&amp;&amp;(K.j.Aa||Array.prototype.lastIndexOf)?function(b,c,d){return Array.prototype.lastIndexOf.call(b,c,null==d?b.length-1:d)}:function(b,c,d){d=null==d?b.length-1:d;0&gt;d&amp;&amp;(d=Math.max(0,b.length+d));if(K.L(b))return K.L(c)&amp;&amp;1==c.length?b.lastIndexOf(c,d):-1;for(;0&lt;=d;d--)if(d in b&amp;&amp;b[d]===c)return d;return-1};
K.j.forEach=K.Ca&amp;&amp;(K.j.Aa||Array.prototype.forEach)?function(b,c,d){Array.prototype.forEach.call(b,c,d)}:function(b,c,d){for(var e=b.length,f=K.L(b)?b.split(""):b,g=0;g&lt;e;g++)g in f&amp;&amp;c.call(d,f[g],g,b)};K.j.Jf=function(b,c){for(var d=K.L(b)?b.split(""):b,e=b.length-1;0&lt;=e;--e)e in d&amp;&amp;c.call(void 0,d[e],e,b)};
K.j.filter=K.Ca&amp;&amp;(K.j.Aa||Array.prototype.filter)?function(b,c,d){return Array.prototype.filter.call(b,c,d)}:function(b,c,d){for(var e=b.length,f=[],g=0,h=K.L(b)?b.split(""):b,l=0;l&lt;e;l++)if(l in h){var m=h[l];c.call(d,m,l,b)&amp;&amp;(f[g++]=m)}return f};K.j.map=K.Ca&amp;&amp;(K.j.Aa||Array.prototype.map)?function(b,c,d){return Array.prototype.map.call(b,c,d)}:function(b,c,d){for(var e=b.length,f=Array(e),g=K.L(b)?b.split(""):b,h=0;h&lt;e;h++)h in g&amp;&amp;(f[h]=c.call(d,g[h],h,b));return f};
K.j.reduce=K.Ca&amp;&amp;(K.j.Aa||Array.prototype.reduce)?function(b,c,d,e){e&amp;&amp;(c=K.bind(c,e));return Array.prototype.reduce.call(b,c,d)}:function(b,c,d,e){var f=d;K.j.forEach(b,function(d,h){f=c.call(e,f,d,h,b)});return f};K.j.reduceRight=K.Ca&amp;&amp;(K.j.Aa||Array.prototype.reduceRight)?function(b,c,d,e){e&amp;&amp;(c=K.bind(c,e));return Array.prototype.reduceRight.call(b,c,d)}:function(b,c,d,e){var f=d;K.j.Jf(b,function(d,h){f=c.call(e,f,d,h,b)});return f};
K.j.some=K.Ca&amp;&amp;(K.j.Aa||Array.prototype.some)?function(b,c,d){return Array.prototype.some.call(b,c,d)}:function(b,c,d){for(var e=b.length,f=K.L(b)?b.split(""):b,g=0;g&lt;e;g++)if(g in f&amp;&amp;c.call(d,f[g],g,b))return!0;return!1};K.j.every=K.Ca&amp;&amp;(K.j.Aa||Array.prototype.every)?function(b,c,d){return Array.prototype.every.call(b,c,d)}:function(b,c,d){for(var e=b.length,f=K.L(b)?b.split(""):b,g=0;g&lt;e;g++)if(g in f&amp;&amp;!c.call(d,f[g],g,b))return!1;return!0};
K.j.count=function(b,c,d){var e=0;K.j.forEach(b,function(b,g,h){c.call(d,b,g,h)&amp;&amp;++e},d);return e};K.j.find=function(b,c,d){c=K.j.findIndex(b,c,d);return 0&gt;c?null:K.L(b)?b.charAt(c):b[c]};K.j.findIndex=function(b,c,d){for(var e=b.length,f=K.L(b)?b.split(""):b,g=0;g&lt;e;g++)if(g in f&amp;&amp;c.call(d,f[g],g,b))return g;return-1};K.j.Iq=function(b,c,d){c=K.j.Aj(b,c,d);return 0&gt;c?null:K.L(b)?b.charAt(c):b[c]};
K.j.Aj=function(b,c,d){for(var e=K.L(b)?b.split(""):b,f=b.length-1;0&lt;=f;f--)if(f in e&amp;&amp;c.call(d,e[f],f,b))return f;return-1};K.j.contains=function(b,c){return 0&lt;=K.j.indexOf(b,c)};K.j.Sb=function(b){return 0==b.length};K.j.clear=function(b){if(!K.isArray(b))for(var c=b.length-1;0&lt;=c;c--)delete b[c];b.length=0};K.j.tr=function(b,c){K.j.contains(b,c)||b.push(c)};K.j.vg=function(b,c,d){K.j.splice(b,d,0,c)};K.j.vr=function(b,c,d){K.fb(K.j.splice,b,d,0).apply(null,c)};
K.j.insertBefore=function(b,c,d){var e;2==arguments.length||0&gt;(e=K.j.indexOf(b,d))?b.push(c):K.j.vg(b,c,e)};K.j.remove=function(b,c){c=K.j.indexOf(b,c);var d;(d=0&lt;=c)&amp;&amp;K.j.Cb(b,c);return d};K.j.Qs=function(b,c){c=K.j.lastIndexOf(b,c);return 0&lt;=c?(K.j.Cb(b,c),!0):!1};K.j.Cb=function(b,c){return 1==Array.prototype.splice.call(b,c,1).length};K.j.Ps=function(b,c,d){c=K.j.findIndex(b,c,d);return 0&lt;=c?(K.j.Cb(b,c),!0):!1};
K.j.Ms=function(b,c,d){var e=0;K.j.Jf(b,function(f,g){c.call(d,f,g,b)&amp;&amp;K.j.Cb(b,g)&amp;&amp;e++});return e};K.j.concat=function(b){return Array.prototype.concat.apply([],arguments)};K.j.join=function(b){return Array.prototype.concat.apply([],arguments)};K.j.vh=function(b){var c